meta_product_name: "VotreVote"
meta_title: "VotreVote - Participez aux décisions locales de votre communauté"
meta_description: "VotreVote est un plateforme dédié aux communes pour faire participer les citoyens dans les décisions de la ville.
"
meta_image: "facebook_card.jpg" # should exist in `app/assets/images/`


